// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAi8nyZqWQkfAbHiC-FAwko5nqxdM7U73M',
    appId: '1:1084786956956:web:391cf37cf85df3e005ab59',
    messagingSenderId: '1084786956956',
    projectId: 'fir-test-project-e9fea',
    authDomain: 'fir-test-project-e9fea.firebaseapp.com',
    databaseURL: 'https://fir-test-project-e9fea-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-test-project-e9fea.appspot.com',
    measurementId: 'G-VHZWCVVM3Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBofoETNR4KLFFpFp6PD0nGErawYIVWeMg',
    appId: '1:1084786956956:android:2fd4d16b730e9d5605ab59',
    messagingSenderId: '1084786956956',
    projectId: 'fir-test-project-e9fea',
    databaseURL: 'https://fir-test-project-e9fea-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-test-project-e9fea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUE1oOYvLJCP7mEYPM17aghAWFGoGuaqQ',
    appId: '1:1084786956956:ios:93d08b31051802d505ab59',
    messagingSenderId: '1084786956956',
    projectId: 'fir-test-project-e9fea',
    databaseURL: 'https://fir-test-project-e9fea-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-test-project-e9fea.appspot.com',
    androidClientId: '1084786956956-tto9djkcu93cijihv5u9qbc5te9vg0r2.apps.googleusercontent.com',
    iosClientId: '1084786956956-2e8ujlcvit56hk62v9ishl5ut8v92ne4.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseTestProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUE1oOYvLJCP7mEYPM17aghAWFGoGuaqQ',
    appId: '1:1084786956956:ios:21b4f1414c1bec1805ab59',
    messagingSenderId: '1084786956956',
    projectId: 'fir-test-project-e9fea',
    databaseURL: 'https://fir-test-project-e9fea-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-test-project-e9fea.appspot.com',
    androidClientId: '1084786956956-tto9djkcu93cijihv5u9qbc5te9vg0r2.apps.googleusercontent.com',
    iosClientId: '1084786956956-up8o14hokfftif8vmeqnitmafv8cdguq.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseTestProject.RunnerTests',
  );
}
